version: "3"
services:
  minecraft:
    container_name: minecraft
    ports:
      - 25565:25565
      - 25575:25575
    volumes:
      - mc:/data
    environment:
      EULA: "TRUE"
      MAX_MEMORY: ${MINECRAFT_MEM}
      CONSOLE: "true"
      TYPE: YATOPIA
      RELEASE: stable
      RCON_PASSWORD:
      ENABLE_QUERY: "true"
      OVERRIDE_SERVER_PROPERTIES: "true"
      ICON: https://static.wikia.nocookie.net/minecraft_gamepedia/images/1/12/Grass_Block_JE2.png/revision/latest/scale-to-width-down/300?cb=20200830142618
      OVERRIDE_ICON: "TRUE"
      ONLINE_MODE: "FALSE"
      USE_AIKAR_FLAGS: "TRUE"
      OPS: ${MINECRAFT_OPS}
    image: itzg/minecraft-server:java15
    stdin_open: true
    tty: true
volumes:
  mc:
